/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendaResponsavelRouteImport } from './routes/venda-responsavel'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as IndexRouteImport } from './routes/index'

const VendaResponsavelRoute = VendaResponsavelRouteImport.update({
  id: '/venda-responsavel',
  path: '/venda-responsavel',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/termos': typeof TermosRoute
  '/venda-responsavel': typeof VendaResponsavelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/termos': typeof TermosRoute
  '/venda-responsavel': typeof VendaResponsavelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/termos': typeof TermosRoute
  '/venda-responsavel': typeof VendaResponsavelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/politica-privacidade' | '/termos' | '/venda-responsavel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/politica-privacidade' | '/termos' | '/venda-responsavel'
  id:
    | '__root__'
    | '/'
    | '/politica-privacidade'
    | '/termos'
    | '/venda-responsavel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  TermosRoute: typeof TermosRoute
  VendaResponsavelRoute: typeof VendaResponsavelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/venda-responsavel': {
      id: '/venda-responsavel'
      path: '/venda-responsavel'
      fullPath: '/venda-responsavel'
      preLoaderRoute: typeof VendaResponsavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  TermosRoute: TermosRoute,
  VendaResponsavelRoute: VendaResponsavelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
